name: Build and Publish Docker Image

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  SUPPORT_URL: ${{ vars.SUPPORT_URL }}
  RABBIT_MQ_STOMP_URL: ${{ vars.RABBIT_MQ_STOMP_URL }}
  RABBIT_MQ_STOMP_USERNAME: ${{ vars.RABBIT_MQ_STOMP_USERNAME }}
  RABBIT_MQ_STOMP_PASSWORD: ${{ secrets.RABBIT_MQ_STOMP_PASSWORD }}
  FAMA_VERSION: ${{ github.ref_name }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  docker:
    name: Build & Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: ‚§µÔ∏è Checkout
        uses: actions/checkout@v4

      - name: üîê Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: üñ•Ô∏è Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: üê≥ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: üêò Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew generateBuildConfig jar --no-daemon -P version="$FAMA_VERSION"

      - name: Verify Build Artifacts
        run: ls -lah build/libs/

      - name: üöÄ Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/aarch64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/fama:${{ github.ref_name }}
